// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YDots.DON.Infrastructure.Persistence;

#nullable disable

namespace YDots.DON.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DonDbContext))]
    partial class DonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YDots.DON.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_campaigns");

                    b.HasIndex("OrganisationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_don_campaigns_org_code");

                    b.ToTable("don_campaigns", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapturedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("captured_by_name");

                    b.Property<Guid>("CapturedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("captured_by_user_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("channel");

                    b.Property<string>("ConsentState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("consent_state");

                    b.Property<string>("ContactRestrictions")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("contact_restrictions");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<string>("EvidenceReference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("evidence_reference");

                    b.Property<string>("EvidenceSource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evidence_source");

                    b.Property<DateTimeOffset?>("ExpiryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_at_utc");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NoticeVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("notice_version");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<bool>("PublicRecognitionPreference")
                        .HasColumnType("boolean")
                        .HasColumnName("public_recognition_preference");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededByConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_consent_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_don_consents");

                    b.HasIndex("EffectiveAtUtc")
                        .HasDatabaseName("ix_don_consents_effective");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_don_consents_lead");

                    b.HasIndex("DonorId", "Channel", "Status")
                        .HasDatabaseName("ix_don_consents_donor_channel_status");

                    b.ToTable("don_consents", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("approval_state");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("archive_reason");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("DoNotContact")
                        .HasColumnType("boolean")
                        .HasColumnName("do_not_contact");

                    b.Property<string>("DonorNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donor_number");

                    b.Property<string>("DonorType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("donor_type");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("MergedIntoDonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_donor_id");

                    b.Property<string>("NormalizedBusinessKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_business_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text")
                        .HasColumnName("organisation_name");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text")
                        .HasColumnName("primary_email");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("text")
                        .HasColumnName("primary_phone");

                    b.Property<string>("RelationshipOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("relationship_owner_name");

                    b.Property<Guid?>("RelationshipOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_owner_user_id");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donors");

                    b.HasIndex("RelationshipOwnerUserId")
                        .HasDatabaseName("ix_don_donors_owner");

                    b.HasIndex("OrganisationId", "DonorNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_don_donors_org_donor_number");

                    b.HasIndex("OrganisationId", "NormalizedBusinessKey")
                        .HasDatabaseName("ix_don_donors_org_business_key");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_don_donors_status_updated");

                    b.ToTable("don_donors", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action_code");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("result");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_audit_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_don_audit_events_correlation");

                    b.HasIndex("OrganisationId", "CreatedAtUtc")
                        .HasDatabaseName("ix_don_audit_events_org_created");

                    b.HasIndex("TargetType", "TargetId", "CreatedAtUtc")
                        .HasDatabaseName("ix_don_audit_events_target");

                    b.ToTable("don_audit_events", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("value");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_contacts");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("ix_don_donor_contacts_donor");

                    b.ToTable("don_donor_contacts", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reference");

                    b.Property<string>("ScanStatus")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("scan_status");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_documents");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("ix_don_donor_documents_donor");

                    b.ToTable("don_donor_documents", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorDonationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("RefreshedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshed_at_utc");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_donation_summaries");

                    b.HasIndex("DonorId", "Stage", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_don_donation_summaries_donor_stage");

                    b.ToTable("don_donor_donation_summaries", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorIdentityVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("ChallengeCodeHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("challenge_code_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("EvidenceReference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("evidence_reference");

                    b.Property<DateTimeOffset?>("ExpiryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_at_utc");

                    b.Property<string>("IdentityConfidence")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("identity_confidence");

                    b.Property<string>("MaskedDestination")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("masked_destination");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_name");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_user_id");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("VerificationChannel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("verification_channel");

                    b.Property<string>("VerificationPurpose")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("verification_purpose");

                    b.Property<string>("VerificationReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("verification_reference");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_identity_verifications");

                    b.HasIndex("VerificationReference")
                        .IsUnique()
                        .HasDatabaseName("ix_don_verifications_reference");

                    b.HasIndex("DonorId", "Status")
                        .HasDatabaseName("ix_don_verifications_donor_status");

                    b.ToTable("don_donor_identity_verifications", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("interaction_type");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("outcome");

                    b.Property<string>("PerformedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("performed_by_name");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_interactions");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_don_donor_interactions_lead");

                    b.HasIndex("DonorId", "OccurredAtUtc")
                        .HasDatabaseName("ix_don_donor_interactions_donor_occurred");

                    b.ToTable("don_donor_interactions", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorMergeCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateADonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_a_donor_id");

                    b.Property<Guid>("CandidateBDonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_b_donor_id");

                    b.Property<string>("ConflictingFields")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("conflicting_fields");

                    b.Property<string>("ConsentImpact")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("consent_impact");

                    b.Property<string>("ContactComparison")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contact_comparison");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("DecidedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("decided_by_name");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DonationHistoryImpact")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("donation_history_impact");

                    b.Property<string>("IdentityConfidence")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("identity_confidence");

                    b.Property<string>("MatchingEvidence")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("matching_evidence");

                    b.Property<string>("MergePreview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("merge_preview");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("ReviewReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("review_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SurvivingDonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("surviving_donor_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_merge_cases");

                    b.HasIndex("CandidateBDonorId")
                        .HasDatabaseName("ix_don_donor_merge_cases_candidate_b_donor_id");

                    b.HasIndex("ReviewReference")
                        .IsUnique()
                        .HasDatabaseName("ix_don_merge_cases_reference");

                    b.HasIndex("CandidateADonorId", "CandidateBDonorId")
                        .HasDatabaseName("ix_don_merge_cases_pair");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_don_merge_cases_status_updated");

                    b.ToTable("don_donor_merge_cases", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorPromise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("PromisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promised_at_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_promises");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_don_donor_promises_campaign_id");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("ix_don_donor_promises_donor");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_don_donor_promises_reference");

                    b.ToTable("don_donor_promises", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_donor_tags");

                    b.HasIndex("DonorId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_don_donor_tags_donor_code");

                    b.ToTable("don_donor_tags", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.FollowUpTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletionOutcome")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("completion_outcome");

                    b.Property<DateTimeOffset?>("ConsentAcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_acknowledged_at_utc");

                    b.Property<string>("ConsentNoticeVersion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("consent_notice_version");

                    b.Property<bool>("ConsentWarningAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_warning_acknowledged");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("FollowUpReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("follow_up_reference");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("NextAction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("next_action");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PermittedChannel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permitted_channel");

                    b.Property<DateTimeOffset?>("PreferredContactTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_contact_time_utc");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("priority");

                    b.Property<string>("Purpose")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("purpose");

                    b.Property<string>("RelationshipOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("relationship_owner_name");

                    b.Property<Guid>("RelationshipOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_owner_user_id");

                    b.Property<string>("RescheduleReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reschedule_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_follow_up_tasks");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("ix_don_follow_up_tasks_donor_id");

                    b.HasIndex("FollowUpReference")
                        .IsUnique()
                        .HasDatabaseName("ix_don_follow_ups_reference");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_don_follow_up_tasks_lead_id");

                    b.HasIndex("RelationshipOwnerUserId")
                        .HasDatabaseName("ix_don_follow_ups_owner");

                    b.HasIndex("Status", "DueAtUtc")
                        .HasDatabaseName("ix_don_follow_ups_status_due");

                    b.ToTable("don_follow_up_tasks", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("resource_reference");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_idempotency_keys");

                    b.HasIndex("OrganisationId", "Key", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_don_idempotency_key_endpoint");

                    b.ToTable("don_idempotency_keys", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("closure_reason");

                    b.Property<string>("ConsentEvidenceReference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consent_evidence_reference");

                    b.Property<string>("ConsentState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("consent_state");

                    b.Property<DateTimeOffset?>("ConvertedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at_utc");

                    b.Property<Guid?>("ConvertedDonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_donor_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DuplicateCandidateSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("duplicate_candidate_summary");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("GeographyCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("geography_code");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("LastContactOutcome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_contact_outcome");

                    b.Property<DateTimeOffset?>("LastContactedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_contacted_at_utc");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LeadReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lead_reference");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("NextAction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("next_action");

                    b.Property<DateTimeOffset?>("NextActionDueUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_due_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("PreferredContactTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_contact_time_utc");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTimeOffset?>("QualifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qualified_at_utc");

                    b.Property<string>("SlaState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sla_state");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("team_code");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_leads");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_don_leads_campaign");

                    b.HasIndex("EmailAddress")
                        .HasDatabaseName("ix_don_leads_email");

                    b.HasIndex("MobileNumber")
                        .HasDatabaseName("ix_don_leads_mobile");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_don_leads_owner");

                    b.HasIndex("OrganisationId", "LeadReference")
                        .IsUnique()
                        .HasDatabaseName("ix_don_leads_org_reference");

                    b.HasIndex("Status", "NextActionDueUtc")
                        .HasDatabaseName("ix_don_leads_status_due");

                    b.ToTable("don_leads", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.LeadAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("assignment_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<bool>("IsBulkRoute")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bulk_route");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("NewOwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("new_owner_name");

                    b.Property<Guid>("NewOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_owner_user_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PreviousOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("previous_owner_name");

                    b.Property<Guid?>("PreviousOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_owner_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_lead_assignments");

                    b.HasIndex("NewOwnerUserId")
                        .HasDatabaseName("ix_don_lead_assignments_owner");

                    b.HasIndex("LeadId", "EffectiveAtUtc")
                        .HasDatabaseName("ix_don_lead_assignments_lead_effective");

                    b.ToTable("don_lead_assignments", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_don_outbox_messages");

                    b.HasIndex("AggregateType", "AggregateId")
                        .HasDatabaseName("ix_don_outbox_aggregate");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_don_outbox_unprocessed");

                    b.ToTable("don_outbox_messages", (string)null);
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Consent", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany("Consents")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_don_consents_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorContact", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany("Contacts")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_contacts_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorDocument", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_documents_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorDonationSummary", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_donation_summaries_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorIdentityVerification", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_identity_verifications_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorInteraction", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany("Interactions")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_don_donor_interactions_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorMergeCase", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "CandidateADonor")
                        .WithMany()
                        .HasForeignKey("CandidateADonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_merge_cases_don_donors_candidate_a_donor_id");

                    b.HasOne("YDots.DON.Domain.Entities.Donor", "CandidateBDonor")
                        .WithMany()
                        .HasForeignKey("CandidateBDonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_merge_cases_don_donors_candidate_b_donor_id");

                    b.Navigation("CandidateADonor");

                    b.Navigation("CandidateBDonor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorPromise", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_don_donor_promises_don_campaigns_campaign_id");

                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_promises_don_donors_donor_id");

                    b.Navigation("Campaign");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.DonorTag", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany("Tags")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_don_donor_tags_don_donors_donor_id");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.FollowUpTask", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_don_follow_up_tasks_don_donors_donor_id");

                    b.HasOne("YDots.DON.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_don_follow_up_tasks_leads_lead_id");

                    b.Navigation("Donor");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Lead", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Leads")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_don_leads_don_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.LeadAssignment", b =>
                {
                    b.HasOne("YDots.DON.Domain.Entities.Lead", "Lead")
                        .WithMany("Assignments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_don_lead_assignments_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Donor", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Contacts");

                    b.Navigation("Interactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("YDots.DON.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
