// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YDot.PAY.Infrastructure.Persistence;

#nullable disable

namespace YDot.PAY.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260827212102_PaymentsSchema")]
    partial class PaymentsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YDot.PAY.Domain.Entities.ChargebackCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CaseReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("case_reference");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<string>("EvidenceDocumentUrls")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence_document_urls");

                    b.Property<DateTimeOffset?>("EvidenceDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_due_at_utc");

                    b.Property<DateTimeOffset?>("EvidenceSubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_submitted_at_utc");

                    b.Property<Guid?>("EvidenceSubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_submitted_by_user_id");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence_summary");

                    b.Property<string>("GatewayDisputeReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_dispute_reference");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_description");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_chargeback_cases");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_pay_chargeback_cases_assignee")
                        .HasFilter("assigned_to_user_id IS NOT NULL");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ix_pay_chargeback_cases_donation");

                    b.HasIndex("GatewayDisputeReference")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_chargeback_cases_dispute")
                        .HasFilter("gateway_dispute_reference IS NOT NULL");

                    b.HasIndex("TenantId", "CaseReference")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_chargeback_cases_reference");

                    b.HasIndex("TenantId", "Status", "EvidenceDueAtUtc")
                        .HasDatabaseName("ix_pay_chargeback_cases_tenant_due");

                    b.ToTable("pay_chargeback_cases", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_chargeback_cases_amount", "disputed_amount > 0");

                            t.HasCheckConstraint("ck_pay_chargeback_cases_evidence", "evidence_submitted_at_utc IS NULL OR evidence_submitted_by_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_pay_chargeback_cases_fee", "chargeback_fee IS NULL OR chargeback_fee >= 0");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<DateTimeOffset>("DonatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donated_at_utc");

                    b.Property<Guid>("DonationIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_intent_id");

                    b.Property<string>("DonationReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("donation_reference");

                    b.Property<string>("DonorAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("donor_address");

                    b.Property<string>("DonorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("donor_email");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("DonorMobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("donor_mobile");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("donor_name");

                    b.Property<string>("DonorTaxIdentifier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("donor_tax_identifier");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("MethodType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method_type");

                    b.Property<Guid>("PaymentAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_attempt_id");

                    b.Property<DateTimeOffset?>("ReconciledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciled_at_utc");

                    b.Property<string>("ReconciliationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reconciliation_note");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reconciliation_status");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at_utc");

                    b.Property<string>("SettlementBatchReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("settlement_batch_reference");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("settlement_status");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TrackingAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_asset_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_donations");

                    b.HasIndex("DonationIntentId")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_donations_intent");

                    b.HasIndex("DonationReference")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_donations_reference");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("ix_pay_donations_donor")
                        .HasFilter("donor_id IS NOT NULL");

                    b.HasIndex("PaymentAttemptId")
                        .HasDatabaseName("ix_pay_donations_payment_attempt_id");

                    b.HasIndex("TenantId", "CampaignId")
                        .HasDatabaseName("ix_pay_donations_tenant_campaign");

                    b.HasIndex("TenantId", "ReconciliationStatus")
                        .HasDatabaseName("ix_pay_donations_tenant_reconciliation");

                    b.HasIndex("TenantId", "Status", "DonatedAtUtc")
                        .HasDatabaseName("ix_pay_donations_tenant_status_date");

                    b.ToTable("pay_donations", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_donations_amount", "amount > 0");

                            t.HasCheckConstraint("ck_pay_donations_fee", "gateway_fee IS NULL OR gateway_fee >= 0");

                            t.HasCheckConstraint("ck_pay_donations_refunded", "refunded_amount >= 0 AND refunded_amount <= amount");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.DonationIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address_line2");

                    b.Property<bool>("AllowPublicRecognition")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_public_recognition");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_given");

                    b.Property<DateTimeOffset?>("ConsentGivenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_given_at_utc");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_version");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("donor_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExistingDonorCheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("existing_donor_checked_at_utc");

                    b.Property<bool?>("ExistingDonorMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("existing_donor_matched");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IntentReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("intent_reference");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalised_email");

                    b.Property<DateTimeOffset?>("PaymentLinkExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_link_expires_at_utc");

                    b.Property<string>("PaymentLinkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("payment_link_url");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("PublicRecognitionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("public_recognition_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_identifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TrackingAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_asset_id");

                    b.Property<string>("TrackingReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracking_reference");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_donation_intents");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_pay_donation_intents_campaign");

                    b.HasIndex("IntentReference")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_donation_intents_reference");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_pay_donation_intents_lead")
                        .HasFilter("lead_id IS NOT NULL");

                    b.HasIndex("TenantId", "NormalisedEmail")
                        .HasDatabaseName("ix_pay_donation_intents_tenant_email");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_pay_donation_intents_tenant_status");

                    b.ToTable("pay_donation_intents", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_donation_intents_amount", "amount > 0");

                            t.HasCheckConstraint("ck_pay_donation_intents_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_pay_donation_intents_consent", "consent_given = false OR consent_given_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("AuthorisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorised_at_utc");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DonationIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_intent_id");

                    b.Property<string>("DonorFacingMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("donor_facing_message");

                    b.Property<string>("DonorIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("donor_ip_address");

                    b.Property<string>("DonorUserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("donor_user_agent");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("GatewayMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("gateway_message");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway_name");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<string>("GatewayResultCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_result_code");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("InitiatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at_utc");

                    b.Property<string>("MaskedInstrument")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("masked_instrument");

                    b.Property<string>("MethodType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_payment_attempts");

                    b.HasIndex("GatewayReference")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_payment_attempts_gateway_reference")
                        .HasFilter("gateway_reference IS NOT NULL");

                    b.HasIndex("DonationIntentId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_payment_attempts_intent_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_pay_payment_attempts_tenant_status");

                    b.ToTable("pay_payment_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_payment_attempts_number", "attempt_number > 0");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action_code");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pay_audit_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_pay_audit_events_correlation")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("ActionCode", "OccurredAtUtc")
                        .HasDatabaseName("ix_pay_audit_events_action");

                    b.HasIndex("Result", "OccurredAtUtc")
                        .HasDatabaseName("ix_pay_audit_events_result");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_pay_audit_events_target");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_pay_audit_events_tenant_occurred");

                    b.ToTable("pay_audit_events", (string)null);
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DismissalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dismissal_reason");

                    b.Property<Guid?>("DismissedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("dismissed_by_user_id");

                    b.Property<Guid?>("DonationIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_intent_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("GatewayEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_event_id");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway_name");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("PaymentAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_attempt_id");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("processing_error");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<bool>("SignatureVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_verified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_payment_events");

                    b.HasIndex("GatewayReference")
                        .HasDatabaseName("ix_pay_payment_events_gateway_reference")
                        .HasFilter("gateway_reference IS NOT NULL");

                    b.HasIndex("PaymentAttemptId")
                        .HasDatabaseName("ix_pay_payment_events_payment_attempt_id");

                    b.HasIndex("GatewayName", "GatewayEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_pay_payment_events_gateway_event");

                    b.HasIndex("Status", "ReceivedAtUtc")
                        .HasDatabaseName("ix_pay_payment_events_status_received");

                    b.ToTable("pay_payment_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_payment_events_attempts", "processing_attempts >= 0");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentGatewayAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key_reference");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EnabledMethods")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("enabled_methods");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test_mode");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentLinkValidityMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("payment_link_validity_minutes");

                    b.Property<string>("ReturnUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("return_url");

                    b.Property<string>("SettlementCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("settlement_currency_code")
                        .IsFixedLength();

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WebhookSecretReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("webhook_secret_reference");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_pay_gateway_accounts");

                    b.HasIndex("GatewayName", "MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_gateway_accounts_merchant");

                    b.HasIndex("TenantId", "GatewayName", "IsTestMode")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_gateway_accounts_tenant_gateway");

                    b.ToTable("pay_gateway_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_gateway_accounts_link_validity", "payment_link_validity_minutes > 0 AND payment_link_validity_minutes <= 43200");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CampaignOrFundName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("campaign_or_fund_name");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("document_url");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<string>("DonorAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("donor_address");

                    b.Property<string>("DonorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("donor_email");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("donor_name");

                    b.Property<string>("DonorTaxIdentifier")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("donor_tax_identifier");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("OrganisationTaxReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organisation_tax_reference");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_receipt_id");

                    b.Property<string>("TaxExemptionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_exemption_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_pay_receipts");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ix_pay_receipts_donation");

                    b.HasIndex("SupersedesReceiptId")
                        .HasDatabaseName("ix_pay_receipts_supersedes_receipt_id");

                    b.HasIndex("TenantId", "DeliveryStatus")
                        .HasDatabaseName("ix_pay_receipts_tenant_delivery");

                    b.HasIndex("TenantId", "FinancialYear", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_receipts_number")
                        .HasFilter("receipt_number IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "IssuedAtUtc")
                        .HasDatabaseName("ix_pay_receipts_tenant_status");

                    b.ToTable("pay_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_receipts_amount", "amount > 0");

                            t.HasCheckConstraint("ck_pay_receipts_issued", "status <> 'Issued' OR (receipt_number IS NOT NULL AND issued_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_pay_receipts_version_number", "version_number > 0");

                            t.HasCheckConstraint("ck_pay_receipts_voided", "voided_at_utc IS NULL OR void_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.ReceiptDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_receipt_deliveries");

                    b.HasIndex("ReceiptId", "AttemptedAtUtc")
                        .HasDatabaseName("ix_pay_receipt_deliveries_receipt");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_pay_receipt_deliveries_tenant_status");

                    b.ToTable("pay_receipt_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_receipt_deliveries_failure", "status <> 'Failed' OR failure_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.RefundCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CaseReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("case_reference");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_note");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<string>("GatewayFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("gateway_failure_reason");

                    b.Property<string>("GatewayRefundReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_refund_reference");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_detail");

                    b.Property<bool>("ReceiptCorrected")
                        .HasColumnType("boolean")
                        .HasColumnName("receipt_corrected");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pay_refund_cases");

                    b.HasIndex("DonationId")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_refund_cases_open_per_donation")
                        .HasFilter("status = 'Requested'");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_pay_refund_cases_requested_by");

                    b.HasIndex("TenantId", "CaseReference")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_refund_cases_reference");

                    b.HasIndex("TenantId", "Status", "RequestedAtUtc")
                        .HasDatabaseName("ix_pay_refund_cases_tenant_status");

                    b.ToTable("pay_refund_cases", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_refund_cases_amount", "amount > 0");

                            t.HasCheckConstraint("ck_pay_refund_cases_decision", "decided_at_utc IS NULL OR decided_by_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_pay_refund_cases_rejection", "status <> 'Rejected' OR rejection_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Infrastructure.Persistence.ReceiptNumberCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pay_receipt_number_counters");

                    b.HasIndex("TenantId", "FinancialYear")
                        .IsUnique()
                        .HasDatabaseName("ux_pay_receipt_number_counters_scope");

                    b.ToTable("pay_receipt_number_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_receipt_number_counters_last", "last_number >= 0");
                        });
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.ChargebackCase", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.Donation", "Donation")
                        .WithMany("ChargebackCases")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_chargeback_cases_donations_donation_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "ChargebackFee", b1 =>
                        {
                            b1.Property<Guid>("ChargebackCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("chargeback_fee");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("chargeback_fee_currency_code")
                                .IsFixedLength();

                            b1.HasKey("ChargebackCaseId");

                            b1.ToTable("pay_chargeback_cases");

                            b1.WithOwner()
                                .HasForeignKey("ChargebackCaseId")
                                .HasConstraintName("fk_pay_chargeback_cases_pay_chargeback_cases_id");
                        });

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "DisputedAmount", b1 =>
                        {
                            b1.Property<Guid>("ChargebackCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("disputed_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("disputed_currency_code")
                                .IsFixedLength();

                            b1.HasKey("ChargebackCaseId");

                            b1.ToTable("pay_chargeback_cases");

                            b1.WithOwner()
                                .HasForeignKey("ChargebackCaseId")
                                .HasConstraintName("fk_pay_chargeback_cases_pay_chargeback_cases_id");
                        });

                    b.Navigation("ChargebackFee");

                    b.Navigation("DisputedAmount")
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Donation", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.DonationIntent", "DonationIntent")
                        .WithOne("Donation")
                        .HasForeignKey("YDot.PAY.Domain.Entities.Donation", "DonationIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_donations_donation_intents_donation_intent_id");

                    b.HasOne("YDot.PAY.Domain.Entities.PaymentAttempt", "PaymentAttempt")
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_donations_payment_attempts_payment_attempt_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DonationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.HasKey("DonationId");

                            b1.ToTable("pay_donations");

                            b1.WithOwner()
                                .HasForeignKey("DonationId")
                                .HasConstraintName("fk_pay_donations_pay_donations_id");
                        });

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "GatewayFee", b1 =>
                        {
                            b1.Property<Guid>("DonationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("gateway_fee");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("gateway_fee_currency_code")
                                .IsFixedLength();

                            b1.HasKey("DonationId");

                            b1.ToTable("pay_donations");

                            b1.WithOwner()
                                .HasForeignKey("DonationId")
                                .HasConstraintName("fk_pay_donations_pay_donations_id");
                        });

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "NetAmount", b1 =>
                        {
                            b1.Property<Guid>("DonationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("net_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("net_currency_code")
                                .IsFixedLength();

                            b1.HasKey("DonationId");

                            b1.ToTable("pay_donations");

                            b1.WithOwner()
                                .HasForeignKey("DonationId")
                                .HasConstraintName("fk_pay_donations_pay_donations_id");
                        });

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "RefundedAmount", b1 =>
                        {
                            b1.Property<Guid>("DonationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("refunded_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("refunded_currency_code")
                                .IsFixedLength();

                            b1.HasKey("DonationId");

                            b1.ToTable("pay_donations");

                            b1.WithOwner()
                                .HasForeignKey("DonationId")
                                .HasConstraintName("fk_pay_donations_pay_donations_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("DonationIntent");

                    b.Navigation("GatewayFee");

                    b.Navigation("NetAmount");

                    b.Navigation("PaymentAttempt");

                    b.Navigation("RefundedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.DonationIntent", b =>
                {
                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DonationIntentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.HasKey("DonationIntentId");

                            b1.ToTable("pay_donation_intents");

                            b1.WithOwner()
                                .HasForeignKey("DonationIntentId")
                                .HasConstraintName("fk_pay_donation_intents_pay_donation_intents_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentAttempt", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.DonationIntent", "DonationIntent")
                        .WithMany("Attempts")
                        .HasForeignKey("DonationIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pay_payment_attempts_pay_donation_intents_donation_intent_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "CapturedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("captured_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("captured_currency_code")
                                .IsFixedLength();

                            b1.HasKey("PaymentAttemptId");

                            b1.ToTable("pay_payment_attempts");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAttemptId")
                                .HasConstraintName("fk_pay_payment_attempts_pay_payment_attempts_id");
                        });

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "RequestedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("requested_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("requested_currency_code")
                                .IsFixedLength();

                            b1.HasKey("PaymentAttemptId");

                            b1.ToTable("pay_payment_attempts");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAttemptId")
                                .HasConstraintName("fk_pay_payment_attempts_pay_payment_attempts_id");
                        });

                    b.Navigation("CapturedAmount");

                    b.Navigation("DonationIntent");

                    b.Navigation("RequestedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentEvent", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.PaymentAttempt", "PaymentAttempt")
                        .WithMany("Events")
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pay_payment_events_pay_payment_attempts_payment_attempt_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentEventId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.HasKey("PaymentEventId");

                            b1.ToTable("pay_payment_events");

                            b1.WithOwner()
                                .HasForeignKey("PaymentEventId")
                                .HasConstraintName("fk_pay_payment_events_pay_payment_events_id");
                        });

                    b.Navigation("Amount");

                    b.Navigation("PaymentAttempt");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.Donation", "Donation")
                        .WithMany("Receipts")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_receipts_pay_donations_donation_id");

                    b.HasOne("YDot.PAY.Domain.Entities.Receipt", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pay_receipts_pay_receipts_supersedes_receipt_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.HasKey("ReceiptId");

                            b1.ToTable("pay_receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_pay_receipts_pay_receipts_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.ReceiptDelivery", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Deliveries")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pay_receipt_deliveries_pay_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.RefundCase", b =>
                {
                    b.HasOne("YDot.PAY.Domain.Entities.Donation", "Donation")
                        .WithMany("RefundCases")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_refund_cases_pay_donations_donation_id");

                    b.OwnsOne("YDot.PAY.Domain.Common.MoneyValue", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.HasKey("RefundCaseId");

                            b1.ToTable("pay_refund_cases");

                            b1.WithOwner()
                                .HasForeignKey("RefundCaseId")
                                .HasConstraintName("fk_pay_refund_cases_pay_refund_cases_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Donation", b =>
                {
                    b.Navigation("ChargebackCases");

                    b.Navigation("Receipts");

                    b.Navigation("RefundCases");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.DonationIntent", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.PaymentAttempt", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("YDot.PAY.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
