// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YDots.CAM.Infrastructure.Persistence;

#nullable disable

namespace YDots.CAM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YDots.CAM.Domain.Entities.AttributionCorrectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AttributionChanged")
                        .HasColumnType("boolean")
                        .HasColumnName("attribution_changed");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrentCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_campaign_id");

                    b.Property<Guid?>("CurrentTrackingAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_tracking_asset_id");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_id");

                    b.Property<string>("DonationReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("donation_reference");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid?>("ProposedCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_campaign_id");

                    b.Property<Guid?>("ProposedTrackingAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_tracking_asset_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_attribution_correction_requests");

                    b.HasIndex("DonationId")
                        .IsUnique()
                        .HasDatabaseName("ux_cam_attribution_corrections_open")
                        .HasFilter("is_resolved = false");

                    b.HasIndex("TenantId", "IsResolved")
                        .HasDatabaseName("ix_cam_attribution_corrections_queue");

                    b.ToTable("cam_attribution_correction_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_attribution_corrections_changed", "is_resolved = true OR attribution_changed = false");

                            t.HasCheckConstraint("ck_cam_attribution_corrections_resolution", "(is_resolved = false AND resolved_at_utc IS NULL AND resolved_by_user_id IS NULL) OR (is_resolved = true AND resolved_at_utc IS NOT NULL AND resolved_by_user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.BudgetTargetPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlanPeriod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_period");

                    b.Property<string>("TargetDimension")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_dimension");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_budget_target_plans");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_cam_budget_plans_code");

                    b.HasIndex("TenantId", "OwnerUserId")
                        .HasDatabaseName("ix_cam_budget_plans_owner");

                    b.HasIndex("CampaignId", "PlanPeriod", "TargetDimension")
                        .IsUnique()
                        .HasDatabaseName("ux_cam_budget_plans_dimension");

                    b.ToTable("cam_budget_target_plans", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.BudgetTargetPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("approval_state");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("Assumptions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("assumptions");

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_amount");

                    b.Property<string>("BudgetCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("budget_category");

                    b.Property<Guid>("BudgetTargetPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_target_plan_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_reason");

                    b.Property<DateTimeOffset?>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<int>("ExpectedVolume")
                        .HasColumnType("integer")
                        .HasColumnName("expected_volume");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_cam_budget_target_plan_versions");

                    b.HasIndex("BudgetTargetPlanId")
                        .IsUnique()
                        .HasDatabaseName("ux_cam_budget_plan_versions_approved")
                        .HasFilter("approval_state = 'Approved'");

                    b.HasIndex("BudgetTargetPlanId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_cam_budget_plan_versions_number");

                    b.ToTable("cam_budget_target_plan_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_budget_plan_versions_amounts", "target_amount >= 0 AND budget_amount >= 0 AND expected_volume >= 0");

                            t.HasCheckConstraint("ck_cam_budget_plan_versions_approval", "(approved_by_user_id IS NULL AND approved_at_utc IS NULL) OR (approved_by_user_id IS NOT NULL AND approved_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_cam_budget_plan_versions_submission", "(submitted_by_user_id IS NULL AND submitted_at_utc IS NULL) OR (submitted_by_user_id IS NOT NULL AND submitted_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<decimal?>("BudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_amount");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<int>("DaysBeforeStart")
                        .HasColumnType("integer")
                        .HasColumnName("days_before_start");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FundOrProgramme")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fund_or_programme");

                    b.Property<string>("LifecycleActivation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lifecycle_activation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("PublicDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("public_description");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("purpose");

                    b.Property<TimeOnly>("ReminderTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("reminder_time");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TermsAndNotice")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("terms_and_notice");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaigns");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_campaigns_tenant_code");

                    b.HasIndex("TenantId", "Status", "StartDate")
                        .HasDatabaseName("ix_cam_campaigns_tenant_status_start");

                    b.ToTable("cam_campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_campaigns_budget", "budget_amount IS NULL OR budget_amount >= 0");

                            t.HasCheckConstraint("ck_cam_campaigns_dates", "end_date >= start_date");

                            t.HasCheckConstraint("ck_cam_campaigns_days_before_start", "days_before_start >= 0");

                            t.HasCheckConstraint("ck_cam_campaigns_target", "target_amount >= 0");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_code");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("result");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_cam_audit_events");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_cam_audit_events_tenant_time");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc")
                        .HasDatabaseName("ix_cam_audit_events_target");

                    b.ToTable("cam_audit_events", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaign_channels");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_cam_campaign_channels_channel_id");

                    b.HasIndex("CampaignId", "ChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_campaign_channels_unique");

                    b.ToTable("cam_campaign_channels", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignLifecycleAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action_status");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ClosureSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("closure_summary");

                    b.Property<string>("CommunicationImpact")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("communication_impact");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DetailedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detailed_reason");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<string>("ReasonCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_category");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaign_lifecycle_actions");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_lifecycle_actions_pending_close")
                        .HasFilter("action_type = 'RequestClose' AND action_status = 'Pending'");

                    b.HasIndex("CampaignId", "ActionType", "ActionStatus")
                        .HasDatabaseName("ix_cam_lifecycle_actions_campaign_type_status");

                    b.ToTable("cam_campaign_lifecycle_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_lifecycle_actions_approval", "approved_at_utc IS NULL OR approved_by_user_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaign_owners");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_cam_campaign_owners_owner");

                    b.HasIndex("CampaignId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_campaign_owners_unique");

                    b.ToTable("cam_campaign_owners", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignReadinessBlocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockerNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blocker_note");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid>("CampaignReadinessCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_readiness_check_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaign_readiness_blockers");

                    b.HasIndex("CampaignReadinessCheckId")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_readiness_blockers_open_unique")
                        .HasFilter("is_resolved = false");

                    b.HasIndex("OwnerUserId", "IsResolved")
                        .HasDatabaseName("ix_cam_readiness_blockers_owner");

                    b.ToTable("cam_campaign_readiness_blockers", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_readiness_blockers_resolution", "(is_resolved = false AND resolved_at_utc IS NULL AND resolved_by_user_id IS NULL) OR (is_resolved = true AND resolved_at_utc IS NOT NULL AND resolved_by_user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignReadinessCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("check_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<bool>("RequiredForLaunch")
                        .HasColumnType("boolean")
                        .HasColumnName("required_for_launch");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("success_criteria");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_campaign_readiness_checks");

                    b.HasIndex("CampaignId", "CheckName")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_readiness_checks_campaign_name");

                    b.HasIndex("CampaignId", "RequiredForLaunch", "Status")
                        .HasDatabaseName("ix_cam_readiness_checks_launch_gate");

                    b.ToTable("cam_campaign_readiness_checks", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_channels");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_channels_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_channels_name");

                    b.ToTable("cam_channels", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.Medium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_mediums");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_mediums_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_mediums_name");

                    b.ToTable("cam_mediums", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_sources_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_sources_name");

                    b.ToTable("cam_sources", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTimeOffset>("ActiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_to");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContentTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_tag");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("destination");

                    b.Property<string>("GeneratedUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("generated_url");

                    b.Property<Guid>("MediumId")
                        .HasColumnType("uuid")
                        .HasColumnName("medium_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalReceived")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_received");

                    b.Property<string>("TrackingReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracking_reference");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("usage_count");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_tracking_assets");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_cam_tracking_assets_channel_id");

                    b.HasIndex("MediumId")
                        .HasDatabaseName("ix_cam_tracking_assets_medium_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_cam_tracking_assets_source_id");

                    b.HasIndex("TrackingReference")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_tracking_assets_reference")
                        .HasFilter("tracking_reference IS NOT NULL");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_cam_tracking_assets_campaign_status");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_tracking_assets_tenant_code");

                    b.ToTable("cam_tracking_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_cam_tracking_assets_submitted", "status IN ('Draft') OR submitted_by_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_cam_tracking_assets_usage", "usage_count >= 0 AND total_received >= 0");

                            t.HasCheckConstraint("ck_cam_tracking_assets_window", "active_to > active_from");
                        });
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAssetCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<Guid>("TrackingAssetPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_asset_place_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_cam_tracking_asset_custom_fields");

                    b.HasIndex("TrackingAssetPlaceId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("ix_cam_tracking_asset_custom_fields_unique");

                    b.ToTable("cam_tracking_asset_custom_fields", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAssetPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("destination");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_name");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("TrackingAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_asset_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cam_tracking_asset_places");

                    b.HasIndex("TrackingAssetId")
                        .HasDatabaseName("ix_cam_tracking_asset_places_asset");

                    b.ToTable("cam_tracking_asset_places", (string)null);
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.BudgetTargetPlan", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_budget_target_plans_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.BudgetTargetPlanVersion", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.BudgetTargetPlan", "Plan")
                        .WithMany("Versions")
                        .HasForeignKey("BudgetTargetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_budget_target_plan_versions_cam_budget_target_plans_bud");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignChannel", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Channels")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_channels_campaigns_campaign_id");

                    b.HasOne("YDots.CAM.Domain.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_channels_channels_channel_id");

                    b.Navigation("Campaign");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignLifecycleAction", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("LifecycleActions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_lifecycle_actions_cam_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignOwner", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Owners")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_owners_cam_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignReadinessBlocker", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.CampaignReadinessCheck", "ReadinessCheck")
                        .WithMany("Blockers")
                        .HasForeignKey("CampaignReadinessCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_readiness_blockers_campaign_readiness_checks_c");

                    b.Navigation("ReadinessCheck");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignReadinessCheck", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("ReadinessChecks")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_campaign_readiness_checks_cam_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAsset", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.Campaign", "Campaign")
                        .WithMany("TrackingAssets")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_assets_cam_campaigns_campaign_id");

                    b.HasOne("YDots.CAM.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_assets_cam_channels_channel_id");

                    b.HasOne("YDots.CAM.Domain.Entities.Medium", null)
                        .WithMany()
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_assets_cam_mediums_medium_id");

                    b.HasOne("YDots.CAM.Domain.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_assets_cam_sources_source_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAssetCustomField", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.TrackingAssetPlace", "Place")
                        .WithMany("CustomFields")
                        .HasForeignKey("TrackingAssetPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_asset_custom_fields_tracking_asset_places_trac");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAssetPlace", b =>
                {
                    b.HasOne("YDots.CAM.Domain.Entities.TrackingAsset", "TrackingAsset")
                        .WithMany("Places")
                        .HasForeignKey("TrackingAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cam_tracking_asset_places_cam_tracking_assets_tracking_asse");

                    b.Navigation("TrackingAsset");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.BudgetTargetPlan", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("LifecycleActions");

                    b.Navigation("Owners");

                    b.Navigation("ReadinessChecks");

                    b.Navigation("TrackingAssets");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.CampaignReadinessCheck", b =>
                {
                    b.Navigation("Blockers");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAsset", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("YDots.CAM.Domain.Entities.TrackingAssetPlace", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
