using YDots.CAM.Application.Common.Models;
using YDots.CAM.Domain.Enums;

namespace YDots.CAM.Application.Features.TrackingAssets.DTOs;

// =====================================================================================
// Commands
// =====================================================================================

/// <summary>
/// Creating a tracking asset.
///
/// <c>Code</c> and <c>TrackingReference</c> are both absent. The code is derived from the
/// campaign and the asset type; the tracking reference is generated by the server and is the
/// attribution key a donation carries back - letting a caller choose either would let two
/// assets claim the same gifts.
///
/// <c>Status</c> IS REQUIRED rather than defaulted to Draft. The Generate asset form asks for it
/// and the module brief lists it among the mandatory fields; defaulting it meant a client that
/// omitted the field got a Draft it never asked for, and a Draft asset resolves no scans - so a
/// QR code could be printed against an asset that was never going to work.
///
/// PLACES ARE REQUIRED FOR A QR CODE ON THE OFFLINE CHANNEL and rejected for every other
/// combination. See <c>TrackingAssetCommandHandler.ValidatePlacements</c>.
/// </summary>
public sealed record CreateTrackingAssetRequest(
    Guid CampaignId,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string Destination,
    Guid SourceId,
    Guid MediumId,
    TrackingAssetStatus Status,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    string? ContentTag = null,
    IReadOnlyList<TrackingAssetPlaceRequest>? Places = null);

/// <summary>
/// Editing a tracking asset. Only a Draft may be edited.
///
/// <c>CampaignId</c> is absent: re-pointing an asset at a different campaign would silently
/// re-attribute every gift already credited through its tracking reference.
/// </summary>
public sealed record UpdateTrackingAssetRequest(
    long ExpectedVersion,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string Destination,
    Guid SourceId,
    Guid MediumId,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    string? ContentTag = null,
    IReadOnlyList<TrackingAssetPlaceRequest>? Places = null);

/// <summary>
/// One placement, on either a create or an update.
///
/// <c>Id</c> is null for a new placement and set for an existing one. ONE TYPE FOR BOTH, rather
/// than the near-identical Create and Update pair this replaces: the two differed only in
/// having that nullable Id, and a placement list is replaced wholesale in either case.
///
/// <c>CityId</c> AND <c>StateId</c> STAY OPTIONAL AND ARE FILLED FROM THE CAMPAIGN when the
/// caller leaves them out. The Generate asset form shows both as "From campaign", which is a
/// promise the client cannot keep on its own - it would have to fetch the campaign, read two
/// ids off it and post them back, and a client that skipped that step saved a placement with no
/// location at all. The server has the campaign in hand and fills them in.
/// </summary>
public sealed record TrackingAssetPlaceRequest(
    string PlaceName,
    string Destination,
    Guid? Id = null,
    Guid? CityId = null,
    Guid? StateId = null,
    IReadOnlyList<TrackingAssetCustomFieldRequest>? CustomFields = null);

/// <summary>A name/value pair on one placement.</summary>
public sealed record TrackingAssetCustomFieldRequest(string FieldName, string Value, Guid? Id = null);

/// <summary>
/// The body of a tracking-asset lifecycle transition: submit, approve, activate, deactivate.
///
/// One type for all four, because the ROUTE says which is meant and each route carries its own
/// permission.
/// </summary>
public sealed record TrackingAssetLifecycleRequest(long ExpectedVersion, string? Reason = null);

// =====================================================================================
// Responses
// =====================================================================================

/// <summary>One row of the tracking asset manager.</summary>
public sealed record TrackingAssetListItemResponse(
    Guid Id,
    Guid TenantId,
    string Code,
    string? TrackingReference,
    Guid CampaignId,
    string CampaignCode,
    string CampaignName,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string ChannelName,
    string Destination,
    Guid SourceId,
    string SourceName,
    Guid MediumId,
    string MediumName,
    string? ContentTag,
    TrackingAssetStatus Status,
    string StatusDescription,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,

    /// <summary>Active AND inside its own dates right now. Different from Status alone.</summary>
    bool IsLive,

    /// <summary>
    /// Scans and clicks resolved through this asset's tracking reference.
    ///
    /// A STORED COUNTER, and nothing in CAM increments it: the reference is resolved by the
    /// public donation flow, which lives outside this service. It reads 0 until that flow
    /// reports back. <see cref="TotalReceived"/> and <see cref="DonationCount"/> below are
    /// different - those are read from the donations themselves and are real today.
    /// </summary>
    long UsageCount,

    /// <summary>
    /// Confirmed income attributed to this asset, refunds already deducted.
    ///
    /// READ FROM THE DONATIONS, not from the column of the same name on the row. That column was
    /// never written by anything, so every asset in the manager reported that it had collected
    /// nothing - which is the one number a tracking asset exists to produce.
    /// </summary>
    decimal TotalReceived,

    /// <summary>Confirmed donations attributed to this asset.</summary>
    int DonationCount,

    /// <summary>Distinct donors who gave through this asset.</summary>
    int DonorCount,

    int PlaceCount,
    DateTimeOffset? UpdatedAtUtc,
    long Version);

/// <summary>The full tracking asset record.</summary>
public sealed record TrackingAssetDetailResponse(
    Guid Id,
    Guid TenantId,
    Guid BusinessUnitId,
    string Code,
    string? TrackingReference,
    string? GeneratedUrl,
    Guid CampaignId,
    string CampaignCode,
    string CampaignName,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string ChannelName,
    string Destination,
    Guid SourceId,
    string SourceName,
    Guid MediumId,
    string MediumName,
    string? ContentTag,
    TrackingAssetStatus Status,
    string StatusDescription,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    bool IsLive,

    /// <summary>Scans and clicks. A stored counter the public donation flow owns.</summary>
    long UsageCount,

    /// <summary>Confirmed income attributed to this asset, read from the donations.</summary>
    decimal TotalReceived,

    int DonationCount,
    int DonorCount,

    /// <summary>Refunded and charged-back amounts, already deducted from TotalReceived.</summary>
    decimal RefundedAmount,

    Guid? SubmittedByUserId,
    DateTimeOffset? SubmittedAtUtc,
    Guid? ApprovedByUserId,
    DateTimeOffset? ApprovedAtUtc,
    DateTimeOffset CreatedAtUtc,
    Guid CreatedByUserId,
    DateTimeOffset? UpdatedAtUtc,
    Guid? UpdatedByUserId,
    long Version,
    IReadOnlyList<TrackingAssetPlaceResponse> Places,

    /// <summary>What this caller may do next, including the segregation-of-duties rule.</summary>
    IReadOnlyList<string> PermittedActions);

/// <summary>One placement, with its city and state named rather than left as ids.</summary>
public sealed record TrackingAssetPlaceResponse(
    Guid Id,
    string PlaceName,
    Guid? CityId,
    string? CityName,
    Guid? StateId,
    string? StateName,
    string Destination,
    IReadOnlyList<TrackingAssetCustomFieldResponse> CustomFields);

/// <summary>One custom field on a placement.</summary>
public sealed record TrackingAssetCustomFieldResponse(Guid Id, string FieldName, string Value);

/// <summary>One line of the tracking asset export.</summary>
public sealed record TrackingAssetExportRow(
    string Code,
    string? TrackingReference,
    string CampaignCode,
    string AssetType,
    string ChannelName,
    string SourceName,
    string MediumName,
    string Destination,
    string? GeneratedUrl,
    string Status,
    string ActiveFrom,
    string ActiveTo,
    string UsageCount,
    string TotalReceived,
    string DonationCount);

// =====================================================================================
// Filters
// =====================================================================================

/// <summary>What the tracking asset manager can be narrowed by.</summary>
public sealed class TrackingAssetSearchFilter : PaginationRequest
{
    public Guid? CampaignId { get; set; }

    public TrackingAssetStatus? Status { get; set; }

    public TrackingAssetType? AssetType { get; set; }

    public Guid? ChannelId { get; set; }

    public Guid? SourceId { get; set; }

    public Guid? MediumId { get; set; }

    /// <summary>
    /// Assets that are live right now: Active AND inside their own dates.
    ///
    /// A separate flag rather than a Status filter, because an Active asset whose window closed
    /// last week is precisely the row somebody is looking for when a QR code has stopped
    /// working - and a Status filter would hide it among the ones that are working fine.
    /// </summary>
    public bool? IsLiveNow { get; set; }
}
