using YDots.CAM.Application.Common.Models;
using YDots.CAM.Domain.Enums;

namespace YDots.CAM.Application.Features.TrackingAssets.DTOs;

// =====================================================================================
// Commands
// =====================================================================================

/// <summary>
/// Creating a tracking asset.
///
/// <c>Code</c> and <c>TrackingReference</c> are both absent. The code is derived from the
/// campaign and the asset type; the tracking reference is generated by the server and is the
/// attribution key a donation carries back - letting a caller choose either would let two
/// assets claim the same gifts.
/// </summary>
public sealed record CreateTrackingAssetRequest(
    Guid CampaignId,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string Destination,
    Guid SourceId,
    Guid MediumId,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    string? ContentTag = null,
    TrackingAssetStatus Status = TrackingAssetStatus.Draft,
    IReadOnlyList<TrackingAssetPlaceRequest>? Places = null);

/// <summary>
/// Editing a tracking asset. Only a Draft may be edited.
///
/// <c>CampaignId</c> is absent: re-pointing an asset at a different campaign would silently
/// re-attribute every gift already credited through its tracking reference.
/// </summary>
public sealed record UpdateTrackingAssetRequest(
    long ExpectedVersion,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string Destination,
    Guid SourceId,
    Guid MediumId,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    string? ContentTag = null,
    IReadOnlyList<TrackingAssetPlaceRequest>? Places = null);

/// <summary>
/// One placement, on either a create or an update.
///
/// <c>Id</c> is null for a new placement and set for an existing one. ONE TYPE FOR BOTH, rather
/// than the near-identical Create and Update pair this replaces: the two differed only in
/// having that nullable Id, and a placement list is replaced wholesale in either case.
/// </summary>
public sealed record TrackingAssetPlaceRequest(
    string PlaceName,
    string Destination,
    Guid? Id = null,
    Guid? CityId = null,
    Guid? StateId = null,
    IReadOnlyList<TrackingAssetCustomFieldRequest>? CustomFields = null);

/// <summary>A name/value pair on one placement.</summary>
public sealed record TrackingAssetCustomFieldRequest(string FieldName, string Value, Guid? Id = null);

/// <summary>
/// The body of a tracking-asset lifecycle transition: submit, approve, activate, deactivate.
///
/// One type for all four, because the ROUTE says which is meant and each route carries its own
/// permission.
/// </summary>
public sealed record TrackingAssetLifecycleRequest(long ExpectedVersion, string? Reason = null);

// =====================================================================================
// Responses
// =====================================================================================

/// <summary>One row of the tracking asset manager.</summary>
public sealed record TrackingAssetListItemResponse(
    Guid Id,
    Guid TenantId,
    string Code,
    string? TrackingReference,
    Guid CampaignId,
    string CampaignCode,
    string CampaignName,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string ChannelName,
    string Destination,
    Guid SourceId,
    string SourceName,
    Guid MediumId,
    string MediumName,
    string? ContentTag,
    TrackingAssetStatus Status,
    string StatusDescription,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,

    /// <summary>Active AND inside its own dates right now. Different from Status alone.</summary>
    bool IsLive,

    long UsageCount,
    decimal TotalReceived,
    int PlaceCount,
    DateTimeOffset? UpdatedAtUtc,
    long Version);

/// <summary>The full tracking asset record.</summary>
public sealed record TrackingAssetDetailResponse(
    Guid Id,
    Guid TenantId,
    Guid BusinessUnitId,
    string Code,
    string? TrackingReference,
    string? GeneratedUrl,
    Guid CampaignId,
    string CampaignCode,
    string CampaignName,
    TrackingAssetType AssetType,
    Guid ChannelId,
    string ChannelName,
    string Destination,
    Guid SourceId,
    string SourceName,
    Guid MediumId,
    string MediumName,
    string? ContentTag,
    TrackingAssetStatus Status,
    string StatusDescription,
    DateTimeOffset ActiveFrom,
    DateTimeOffset ActiveTo,
    bool IsLive,
    long UsageCount,
    decimal TotalReceived,
    Guid? SubmittedByUserId,
    DateTimeOffset? SubmittedAtUtc,
    Guid? ApprovedByUserId,
    DateTimeOffset? ApprovedAtUtc,
    DateTimeOffset CreatedAtUtc,
    Guid CreatedByUserId,
    DateTimeOffset? UpdatedAtUtc,
    Guid? UpdatedByUserId,
    long Version,
    IReadOnlyList<TrackingAssetPlaceResponse> Places,

    /// <summary>What this caller may do next, including the segregation-of-duties rule.</summary>
    IReadOnlyList<string> PermittedActions);

/// <summary>One placement.</summary>
public sealed record TrackingAssetPlaceResponse(
    Guid Id,
    string PlaceName,
    Guid? CityId,
    Guid? StateId,
    string Destination,
    IReadOnlyList<TrackingAssetCustomFieldResponse> CustomFields);

/// <summary>One custom field on a placement.</summary>
public sealed record TrackingAssetCustomFieldResponse(Guid Id, string FieldName, string Value);

/// <summary>One line of the tracking asset export.</summary>
public sealed record TrackingAssetExportRow(
    string Code,
    string? TrackingReference,
    string CampaignCode,
    string AssetType,
    string ChannelName,
    string SourceName,
    string MediumName,
    string Destination,
    string? GeneratedUrl,
    string Status,
    string ActiveFrom,
    string ActiveTo,
    string UsageCount,
    string TotalReceived);

// =====================================================================================
// Filters
// =====================================================================================

/// <summary>What the tracking asset manager can be narrowed by.</summary>
public sealed class TrackingAssetSearchFilter : PaginationRequest
{
    public Guid? CampaignId { get; set; }

    public TrackingAssetStatus? Status { get; set; }

    public TrackingAssetType? AssetType { get; set; }

    public Guid? ChannelId { get; set; }

    public Guid? SourceId { get; set; }

    public Guid? MediumId { get; set; }

    /// <summary>
    /// Assets that are live right now: Active AND inside their own dates.
    ///
    /// A separate flag rather than a Status filter, because an Active asset whose window closed
    /// last week is precisely the row somebody is looking for when a QR code has stopped
    /// working - and a Status filter would hide it among the ones that are working fine.
    /// </summary>
    public bool? IsLiveNow { get; set; }
}
